# Generated by Django 3.1.4 on 2020-12-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('abbrev', models.CharField(max_length=16)),
                ('stars', models.IntegerField()),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
