# Generated by Django 3.1.4 on 2020-12-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0003_hotelcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenew.hotelcategory'),
        ),
    ]
