# Generated by Django 3.1.4 on 2020-12-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0004_auto_20201227_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='category',
            field=models.CharField(choices=[('Disney Hotel', 'Disney Hotel'), ('Partner Hotel', 'Partner Hotel')], default=('Disney Hotel', 'Disney Hotel'), max_length=32),
        ),
    ]
