# Generated by Django 3.1.4 on 2020-12-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0006_auto_20201227_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelcategory',
            options={'verbose_name': 'Hotel Category', 'verbose_name_plural': 'Hotel Categories'},
        ),
        migrations.AlterModelOptions(
            name='hotels',
            options={'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterField(
            model_name='hotels',
            name='abbrev',
            field=models.CharField(max_length=16, verbose_name='Abbreviation'),
        ),
        migrations.CreateModel(
            name='CityTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EUR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GBP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('USD', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CHF', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DKK', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenew.hotels')),
            ],
        ),
    ]
