# Generated by Django 3.1.4 on 2020-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0008_auto_20201227_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='citytax',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citytax',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citytax',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
