# Generated by Django 3.1.4 on 2020-12-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0009_auto_20201229_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytax',
            name='end_date',
            field=models.DateField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='citytax',
            name='start_date',
            field=models.DateField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='citytax',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Season'),
        ),
    ]
