# Generated by Django 3.1.4 on 2020-12-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0010_auto_20201229_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Season Title')),
                ('start_date', models.DateField(verbose_name='Start')),
                ('end_date', models.DateField(verbose_name='End')),
            ],
            options={
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.RemoveField(
            model_name='citytax',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='citytax',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='citytax',
            name='title',
        ),
    ]
