# Generated by Django 3.1.4 on 2020-12-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0011_auto_20201229_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='citytax',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revenew.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Season Name'),
        ),
    ]
