# Generated by Django 3.1.4 on 2020-12-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0012_auto_20201229_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytax',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenew.hotels'),
        ),
    ]
