# Generated by Django 3.1.4 on 2020-12-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0013_auto_20201230_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('EUR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DKK', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CHF', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GBP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('USD', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
