# Generated by Django 3.1.4 on 2021-01-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenew', '0014_processingfees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingfees',
            options={'verbose_name_plural': 'Processing Fees'},
        ),
        migrations.AddField(
            model_name='hotels',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
